apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-rails-example-deployment
  labels:
    app: kubernetes-rails-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-rails-example
  template:
    metadata:
      labels:
        app: kubernetes-rails-example
    spec:
      containers:
      - name: kubernetes-rails-example
        image: mrabets/kubernetes-rails-example:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-rails-example-service
spec:
  selector:
    app: kubernetes-rails-example
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
